version: '3.8'

services:
  svelte-randonneur-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svelte-randonneur-app
    ports:
      - "8080:80"
    restart: unless-stopped
    image: svelte-randonneur-app:latest

